language: android

jdk:
  - oraclejdk8

android:
  components:
    - platform-tools-27.1.1
    - tools
    - build-tools-27.0.3
    - android-27

    # Additional components
    # - extra-google-google_play_services
    # - extra-google-m2repository
    # - extra-android-m2repository
    # - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-22
    # - sys-img-armeabi-v7a-android-17

